-   id: prepend-jira-ticket-number
    name: Jira Ticket Number Prepender
    description: Appends ticket number above commit message based on the branch name
    entry: prepend_jira_ticket_number
    language: python
    language_version: python3
    files: ''
    always_run: true
    pass_filenames: true
    stages: [prepare-commit-msg]
    verbose: true
